### ISSUE TITLE
Why is the OData routing policy required?

### ISSUE THREAD

**Issue by davidgeiger** [Axway-API-Management-Plus/odata-routing-policy#19]
It would be very helpful if the project description provided some insights as to why/when the OData routing policy is required and what exactly it does. We have run tests with many OData APIs - with and without the policy - and could not completely determine in which situations it is required.

One thing we've noticed is that mapping the policy disables query parameter reencoding, which helps with a lot of OData APIs. I am not sure if this is just a side effect. Also, I would be interested if the JVM parameter com.coreapireg.apimethod.querystring.passthrough (introduced in 2020-11) provides an out-of-the-box alternative to achieve this.

Thanks - David

**Comment by cwiechmann** [comment]
I still believe the `*` at the end of the exposure path is required. For instance, when using Navigational-Properties like this:

`serviceRoot/People('russellwhyte')/Trips(1001)/PlanItems(11)`

In that case, our standard API-Path only expects: `('russellwhyte')` and method matching will fail because of the remaining part when not having the "*"

The system property is only for the Query-String part. BTW @davidgeiger, we are in discussion with PM to make the toggle: `com.coreapireg.apimethod.querystring.passthrough` API-Specific instead of global.
